FTSApp/FTSApp/urls.py
from django.contrib import admin
from django.urls import path, include
from account_system.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('account/', include('account_system.urls')),
    path("auth/", include('social_django.urls', namespace='social')), 
    path("warikan/", include("warikan.urls")),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FTSApp/warikan/urls.py
from django.urls import path

from . import views

app_name = 'warikan'

urlpatterns = [
    path("index/", views.index, name = "index"), #warikanのindex
    path("event_detail/<uuid:uuid>/", views.event_detail, name = "event_detail"), #イベント詳細ページ
    path('event/<uuid:event_uuid>/payments/<uuid:payment_uuid>/', views.payment_detail, name='payment_detail'),
    path('event/<uuid:event_uuid>/payments/', views.payment_list, name='payment_list'),
    path('event_detail/<uuid:uuid>/confirmation/', views.confirmation, name="confirmation"),
    path('add_event/', views.add_event, name="add_event"),
    path('event/invite/<uuid:event_uuid>/', views.invite, name="invite"),
]

FTSApp/warikan/models.py
from django.db import models
from account_system.models import User
import uuid
from django.utils import timezone

class Event(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20)
    description = models.TextField(max_length=100, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    members = models.ManyToManyField(User)
    registration_stopped = models.BooleanField(default=False)
    thumbnail = models.ImageField(upload_to="images/thumbnail/", blank=True)

    def __str__(self):
        return self.name

class Payment(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20)
    description = models.TextField(max_length=100, blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    payer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="payer")
    payee = models.ManyToManyField(User, related_name="payee")
    created_at = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)
    amount = models.IntegerField(default=0)
    receipt_image = models.ImageField(upload_to="images/receipt/", blank=True)

    def __str__(self) -> str:
        return self.name


# Create your models here.

FTSApp/warikan/forms.py
from django import forms
from .models import Payment, Event
from account_system.models import User


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['name', 'description', 'amount', 'payer', 'payee', 'receipt_image']  # receipt_image を追加
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
        }

    def __init__(self, event, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)
        self.fields['payee'].widget = forms.CheckboxSelectMultiple()  # payeeをチェックボックスで選択できるようにする
        self.fields['payee'].queryset = event.members.all()  # payeeの選択肢をイベントのメンバーに制限する
        self.fields['payer'].queryset = event.members.all()

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'description', 'thumbnail']  
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),  # descriptionフィールドにテキストエリアを使用
        }
    
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # 必要に応じて、カスタム初期化処理をここに追加できます

FTSApp/warikan/views.py
from .models import Event, Payment
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import PaymentForm, EventForm
from .warikan_calculater import calculate_settlement
import json

@login_required
def index(request):
    user = request.user
    events = Event.objects.filter(members=user).order_by('-last_updated')
    return render(request, 'warikan/index.html', {'events': events})


@login_required
def event_detail(request, uuid):
    event = get_object_or_404(Event, uuid=uuid)
    latest_payments = event.payment_set.order_by('-created_at')[:5]

    if request.method == "POST":
        form = PaymentForm(event, request.POST, request.FILES)  # request.FILESを追加
        if form.is_valid():
            payment = form.save(commit=False)
            payment.event = event
            payment.save()
            form.save_m2m()  # ManyToManyフィールドを保存
            return redirect("warikan:event_detail", uuid=event.uuid)
        else:
            print("Form is invalid:", form.errors)
    else:
        form = PaymentForm(event)

    return render(request, 'warikan/event_detail.html', {
        'event': event,
        'form': form,
        'latest_payments': latest_payments
    })


@login_required
def payment_list(request, event_uuid):
    event = get_object_or_404(Event, uuid=event_uuid)
    payments = event.payment_set.all().order_by('-created_at')
    return render(request, 'warikan/payment_list.html', {'event': event, 'payments': payments})

@login_required
def payment_detail(request, event_uuid, payment_uuid):
    event = Event.objects.get(uuid=event_uuid)
    payment = get_object_or_404(Payment, uuid=payment_uuid)

    if request.method == "POST":
        form = PaymentForm(event, request.POST, request.FILES, instance=payment)
        if form.is_valid():
            form.save()
            return redirect('warikan:payment_detail', event_uuid=event_uuid, payment_uuid=payment_uuid)
    else:
        form = PaymentForm(event, instance=payment)
        # payeeフィールドの初期値を設定
        form.fields['payee'].initial = payment.payee.all().values_list('uuid', flat=True)

    return render(request, 'warikan/payment_detail.html', {
        'form': form,
        'event': payment.event
    })


@login_required
def confirmation(request, uuid):
    event = Event.objects.get(uuid=uuid)
    settlements = calculate_settlement(event)
    
    # settlementsのキーをユーザーのusernameに変更
    settlements_dict = {payer.username: {recipient.username: amount for recipient, amount in recipients.items()} for payer, recipients in settlements.items()}
    
    context = {
        'event': event,
        'settlements': json.dumps(settlements_dict),  # 修正後のsettlements_dictを渡す
    }
    return render(request, 'warikan/confirmation.html', context)

@login_required
def add_event(request):
    user = request.user
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)  # 一旦保存を延期
            event.save()  # イベントを保存してから
            event.members.add(user)  # userをmembersに追加
            return redirect('warikan:index')
    else:
        form = EventForm()

    return render(request, 'warikan/add_event.html', {'form': form})

@login_required
def invite(request, event_uuid):
    user = request.user
    event =  Event.objects.get(uuid=event_uuid)
    event.members.add(user)
    return redirect("warikan:index")

# Create your views here.

FTSApp/templates/warikan/add_event.html
{% extends 'base.html' %}

{% block title %}イベント作成{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2>新しいイベントを作成</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">作成</button>
    </form>
</div>
{% endblock %}

FTSApp/templates/warikan/event_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center">
            <h1 class="me-3">{{ event.name }}</h1>
            <button id="copyInviteLink" class="btn btn-outline-primary ms-3 position-relative">招待URL</button>
        </div>
        <a href="{% url 'warikan:confirmation' event.uuid %}" class="btn btn-success">精算確認</a>
    </div>
    <div class="d-flex">
        {% for member in event.members.all %}
        <img src="{{ member.icon_url }}" alt="member-icon" class="rounded-circle member-icon me-1">
        {% endfor %}
    </div>
    <p>更新日時: {{ event.last_updated|date:"Y年m月d日 H:i" }}</p>
    <p>{{ event.description }}</p>

    <div class="row">
        <div class="col-md-6">
            <h2>
                <a href="{% url 'warikan:payment_list' event.uuid %}" style="color: inherit; text-decoration: none;">
                    支払い一覧
                </a>
            </h2>
            <ul class="list-group">
                {% for payment in latest_payments %}
                <li class="list-group-item payment-card" data-url="{% url 'warikan:payment_detail' event.uuid payment.uuid %}">
                    <div class="d-flex justify-content-start align-items-center">
                        <h5 class="mb-0">{{ payment.name }}</h5>
                        <span class="mx-3"></span>
                        <span class="badge bg-primary rounded-pill">{{ payment.amount }}円</span>
                    </div>
                    <div class="d-flex align-items-center mt-2">
                        <img src="{{ payment.payer.icon_url }}" alt="payer-icon" class="rounded-circle icon-border me-2" width="30">
                        <span class="fa fa-arrow-right text-primary me-2"></span>
                        <div class="payee-box d-flex flex-wrap">
                            {% for payee in payment.payee.all %}
                            <img src="{{ payee.icon_url }}" alt="payee-icon" class="rounded-circle icon-border me-2" width="30">
                            {% endfor %}
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <a href="{% url 'warikan:payment_list' event.uuid %}" class="btn btn-link mt-2">全て表示</a>
        </div>
        
        <div class="col-md-6">
            <h2 class="mt-5 mt-md-0">支払い登録</h2>
            <form method="post" enctype="multipart/form-data" class="form-container p-4 border rounded bg-light shadow-sm" action="{% url 'warikan:event_detail' event.uuid %}">
                {% csrf_token %}
                
                <div class="row mb-3 align-items-center">
                    <div class="col-md-5 text-center">
                        <div class="form-group">
                            <label for="id_payer">支払った人:</label>
                            <div class="d-flex align-items-center">
                                {{ form.payer }}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2 text-center">
                        <span class="fa fa-arrow-right text-primary arrow-icon-form"></span>
                    </div>
                    <div class="col-md-5 text-center mt-3 mt-md-0">
                        <div class="form-group">
                            <label for="id_payee">支払われた人:</label>
                            <div class="form-check payee-grid">
                                {% for choice in form.payee.field.queryset %}
                                <div class="d-flex align-items-center mb-2 payee-item">
                                    <input type="checkbox" name="payee" value="{{ choice.pk }}" class="form-check-input me-2" id="payee_{{ choice.pk }}">
                                    <img src="{{ choice.icon_url }}" alt="icon" class="rounded-circle icon-border me-2" width="30">
                                    <label for="payee_{{ choice.pk }}" class="form-check-label">{{ choice }}</label>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_name">支払い名:</label>
                    {{ form.name }}
                </div>

                <div class="form-group">
                    <label for="id_amount">金額:</label>
                    {{ form.amount }}
                </div>

                <div class="form-group">
                    <label for="id_description">説明:</label>
                    {{ form.description }}
                </div>

                <div class="form-group">
                    <label for="id_receipt_image">領収書の画像:</label>
                    {{ form.receipt_image }}
                </div>

                <button type="submit" class="btn btn-primary mt-3">登録する</button>
            </form>
        </div>
    </div>
</div>

<style>
.form-container {
    max-width: 100%; 
    overflow: hidden;
}

.form-group textarea {
    width: 100%;
    resize: vertical;
}

.icon-border {
    border: 1px solid rgba(0, 0, 0, 0.2);
    padding: 2px;
}

.member-icon {
    border: 1px solid rgba(0, 0, 0, 0.2);
    padding: 2px;
    width: 30px;
    height: 30px;
    object-fit: cover;
}

.list-group-item {
    display: flex;
    flex-direction: column;
    cursor: pointer;
}

.payment-card:hover {
    background-color: #f8f9fa;
}

.arrow-icon-list {
    transform: rotate(0deg); 
}

.arrow-icon-form {
    transform: rotate(0deg); 
}

.payee-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); 
    gap: 10px; 
}

.payee-item {
    display: flex;
    align-items: center;
    justify-content: flex-start;
}

@media (max-width: 768px) {
    .arrow-icon-form {
        transform: rotate(90deg);
    }

    .payee-grid {
        grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); 
    }

    .d-flex.align-items-center.justify-content-between {
        flex-direction: column;
        align-items: flex-start;
    }

    .btn-success {
        width: 100%;
        margin-top: 10px;
    }
}

.btn-outline-primary {
    font-size: 0.875rem;  /* 小さめの文字サイズ */
    padding: 0.375rem 0.75rem;
}

#copyInviteLink.copying {
    font-size: 0.75rem;  /* コピー時の文字サイズをさらに小さく */
    padding: 0.25rem 0.5rem;  /* パディングも調整してサイズを合わせる */
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const paymentCards = document.querySelectorAll('.payment-card');
    paymentCards.forEach(function(card) {
        card.addEventListener('click', function() {
            window.location.href = card.getAttribute('data-url');
        });
    });

    const copyButton = document.getElementById('copyInviteLink');
    const originalText = copyButton.innerHTML;
    const inviteUrl = "{{ request.scheme }}://{{ request.get_host }}{% url 'warikan:invite' event.uuid %}";

    copyButton.addEventListener('click', function() {
        const tempInput = document.createElement('input');
        tempInput.value = inviteUrl;
        document.body.appendChild(tempInput);
        tempInput.select();
        document.execCommand('copy');
        document.body.removeChild(tempInput);

        copyButton.classList.add('copying');
        copyButton.innerHTML = "コピーしました";
        setTimeout(function() {
            copyButton.innerHTML = originalText;
            copyButton.classList.remove('copying');
        }, 2000);
    });
});
</script>
{% endblock %}

FTSApp/templates/warikan/index.html
{% extends "base.html" %}

{% block title %}イベント一覧{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h2>イベント一覧</h2>
            <!-- Add event button -->
            <a href="{% url 'warikan:add_event' %}" class="btn btn-primary">イベント追加</a>
        </div>
        <div class="row">
            {% for event in events %}
                <div class="col-md-6 mb-4">
                    <a href="{% url 'warikan:event_detail' event.uuid %}" class="text-decoration-none text-dark">
                        <div class="card">
                            {% if event.thumbnail %}
                            <img src="{{ event.thumbnail.url }}" class="card-img-top" alt="{{ event.name }}のサムネイル" style="object-fit: cover; height: 200px;">
                            {% endif %}
                            <div class="card-body">
                                <div class="d-flex align-items-center mb-2">
                                    <h5 class="card-title mb-0" style="line-height: 1.2;">
                                        {{ event.name }}
                                    </h5>
                                    <div class="ml-3 d-flex align-items-center">
                                        {% for member in event.members.all %}
                                            <img src="{{ member.icon_url }}" alt="LINE Icon" 
                                                 class="rounded-circle ml-1" 
                                                 style="border: 1px solid black; 
                                                        height: 1.5em; 
                                                        width: 1.5em; 
                                                        object-fit: cover;">
                                        {% endfor %}
                                    </div>
                                </div>
                                <h6 class="card-subtitle mb-2 text-muted">更新日時: {{ event.last_updated|date:"Y年n月j日 H:i" }}</h6>
                                <p class="card-text">{{ event.description }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

FTSApp/templates/warikan/payment_detail.html
{% extends 'base.html' %}

{% block title %}支払い詳細{% endblock %}

{% block content %}
<div class="container mt-5">
    <!-- Modify event name to look like regular text but still be a clickable link -->
    <h1>
        <a href="{% url 'warikan:event_detail' event.uuid %}" style="color: inherit; text-decoration: none;">
            {{ event.name }}
        </a>
    </h1>
    
    <h2>支払い詳細</h2>
    <form method="post" enctype="multipart/form-data" class="form-container p-4 border rounded bg-light shadow-sm">
        {% csrf_token %}
        
        <div class="row mb-3 align-items-center">
            <div class="col-md-5 text-center">
                <div class="form-group">
                    <label for="id_payer">支払った人:</label>
                    <div class="d-flex align-items-center">
                        {{ form.payer }}
                    </div>
                </div>
            </div>
            <div class="col-md-2 text-center">
                <span class="fa fa-arrow-right text-primary arrow-icon-form"></span>
            </div>
            <div class="col-md-5 text-center mt-3 mt-md-0">
                <div class="form-group">
                    <label for="id_payee">支払われた人:</label>
                    <div class="form-check payee-grid">
                        {% for choice in form.payee.field.queryset %}
                        <div class="d-flex align-items-center mb-2 payee-item">
                            <input type="checkbox" name="payee" value="{{ choice.pk }}" class="form-check-input me-2" id="payee_{{ choice.pk }}" {% if choice.pk in form.payee.value %}checked{% endif %}>
                            <img src="{{ choice.icon_url }}" alt="icon" class="rounded-circle icon-border me-2" width="30">
                            <label for="payee_{{ choice.pk }}" class="form-check-label">{{ choice }}</label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="id_name">支払い名:</label>
            {{ form.name }}
        </div>

        <div class="form-group">
            <label for="id_amount">金額:</label>
            {{ form.amount }}
        </div>

        <div class="form-group">
            <label for="id_description">説明:</label>
            {{ form.description }}
        </div>

        <div class="form-group">
            <label for="id_receipt_image">領収書の画像:</label>
            {% if form.receipt_image.value %}
            <div class="mb-2">
                <img src="{{ form.receipt_image.value.url }}" alt="領収書の画像" class="img-thumbnail" style="max-width: 100%; height: auto;">
            </div>
            {% endif %}
            {{ form.receipt_image }}
        </div>

        <button type="submit" class="btn btn-primary mt-3">更新する</button>
    </form>
    <!-- Add "イベント詳細に戻る" button next to the "支払い一覧に戻る" button -->
    <a href="{% url 'warikan:payment_list' event.uuid %}" class="btn btn-secondary mt-3">支払い一覧に戻る</a>
    <a href="{% url 'warikan:event_detail' event.uuid %}" class="btn btn-secondary mt-3 ms-2">イベント詳細に戻る</a>
</div>

<style>
.form-container {
    max-width: 100%; 
    overflow: hidden;
}

.form-group textarea {
    width: 100%;
    resize: vertical;
}

.icon-border {
    border: 1px solid rgba(0, 0, 0, 0.2);
    padding: 2px;
}

.member-icon {
    border: 1px solid rgba(0, 0, 0, 0.2);
    padding: 2px;
    width: 30px;
    height: 30px;
    object-fit: cover;
}

.list-group-item {
    display: flex;
    flex-direction: column;
    cursor: pointer;
}

.payment-card:hover {
    background-color: #f8f9fa;
}

.arrow-icon-form {
    transform: rotate(0deg); 
}

.payee-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); 
    gap: 10px; 
}

.payee-item {
    display: flex;
    align-items: center;
    justify-content: flex-start;
}

.img-thumbnail {
    border: 1px solid rgba(0, 0, 0, 0.125);
    padding: 0.25rem;
    background-color: #fff;
    max-height: 300px;
    object-fit: cover;
}

@media (max-width: 768px) {
    .arrow-icon-form {
        transform: rotate(90deg);
    }

    .payee-grid {
        grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); 
    }

    .d-flex.align-items-center.justify-content-between {
        flex-direction: column;
        align-items: flex-start;
    }

    .btn-success {
        width: 100%;
        margin-top: 10px;
    }
}
</style>

{% endblock %}

FTSApp/templates/warikan/payment_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <!-- Separate event.name and 支払い一覧, and make event.name clickable -->
    <div class="d-flex align-items-center justify-content-between">
        <div>
            <h1>
                <a href="{% url 'warikan:event_detail' event.uuid %}" style="color: inherit; text-decoration: none;">
                    {{ event.name }}
                </a>
            </h1>
            <h2>支払い一覧</h2>
        </div>
        <!-- Add 精算確認 button -->
        <a href="{% url 'warikan:confirmation' event.uuid %}" class="btn btn-success">精算確認</a>
    </div>
    <ul class="list-group">
        {% for payment in payments %}
        <li class="list-group-item payment-card" data-url="{% url 'warikan:payment_detail' event.uuid payment.uuid %}">
            <div class="d-flex justify-content-start align-items-center">
                <h5 class="mb-0">{{ payment.name }}</h5>
                <span class="mx-3"></span>
                <span class="badge bg-primary rounded-pill">{{ payment.amount }}円</span>
            </div>
            <div class="d-flex align-items-center mt-2">
                <img src="{{ payment.payer.icon_url }}" alt="payer-icon" class="rounded-circle icon-border me-2" width="30">
                <span class="fa fa-arrow-right text-primary me-2"></span>
                <div class="payee-box d-flex flex-wrap">
                    {% for payee in payment.payee.all %}
                    <img src="{{ payee.icon_url }}" alt="payee-icon" class="rounded-circle icon-border me-2" width="30">
                    {% endfor %}
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'warikan:event_detail' event.uuid %}" class="btn btn-secondary mt-3">イベント詳細に戻る</a>
</div>

<style>
.icon-border {
    border: 1px solid rgba(0, 0, 0, 0.2);
    padding: 2px;
}

.payment-card:hover {
    background-color: #f8f9fa;
}

.payee-box {
    display: flex;
    flex-wrap: wrap;
}

.list-group-item {
    cursor: pointer;
}

@media (max-width: 768px) {
    .payee-box img {
        margin-bottom: 5px;
    }
}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const paymentCards = document.querySelectorAll('.payment-card');
    paymentCards.forEach(function(card) {
        card.addEventListener('click', function() {
            window.location.href = card.getAttribute('data-url');
        });
    });
});
</script>
{% endblock %}